# Generated by Django 5.1.1 on 2024-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('bot_token', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('use_polling', models.BooleanField(default=True)),
            ],
        ),
    ]
