# Generated by Django 5.1.1 on 2024-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0003_remove_usercommunication_preferred_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('chat_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
