# Generated by Django 5.1.1 on 2024-10-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0004_usercommunication'),
        ('web', '0005_alter_blogpost_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'ordering': ['-display_name'], 'verbose_name': 'Параметры E-mail', 'verbose_name_plural': 'Параметры E-mail'},
        ),
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'ordering': ['-bot_name'], 'verbose_name': 'Параметры Telegram бота', 'verbose_name_plural': 'Параметры Telegram ботов'},
        ),
        migrations.AlterModelOptions(
            name='usercommunication',
            options={'ordering': ['-id'], 'verbose_name': 'Связь с клиентом', 'verbose_name_plural': 'Связи с клиентами'},
        ),
        migrations.AddField(
            model_name='usercommunication',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='web.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='usercommunication',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='usercommunication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='usercommunication',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
    ]
