# Generated by Django 5.1.1 on 2024-10-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
