# Generated by Django 5.1.1 on 2024-10-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_order_service_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='related_service_requests', to='web.client'),
            preserve_default=False,
        ),
    ]
