# Generated by Django 5.1.1 on 2024-10-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_order_client_email_remove_order_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
