# Generated by Django 5.1.1 on 2024-10-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_servicerequest_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_service_requests', to='web.client'),
        ),
    ]
