# Generated by Django 5.1.1 on 2024-11-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_servicerequest_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-is_verified', '-created_at'], 'verbose_name': 'Заявка на услугу', 'verbose_name_plural': 'Заявки на услуги'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
